const mongoose = require("mongoose");
const Food = require("./models/foodModel"); // Path to your Food model file
const dotenv = require("dotenv");

// Load environment variables from .env file
dotenv.config();

// Connect to the MongoDB database
mongoose
  .connect(process.env.MONGODB_URI || "mongodb+srv://np03cs4a220226:P8pFKRrJR95zm0H2@fitfuelcluster.ua2aw.mongodb.net/FitFuelDB?retryWrites=true&w=majority&appName=FitFuelCluster", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => console.log("MongoDB connected"))
  .catch((error) => console.log("MongoDB connection error:", error));

// Sample food data to seed
const foodData = [
  {
    name: "Whey Protein",
    amount: "28 gm",
    calories: 500,
    protein: 24,
    carbs: 6,
    fiber: 0,
    sugar: 3,
    fat: 2,
    saturatedFat: 1,
    polyunsaturatedFat: 0.5,
    monounsaturatedFat: 0.5,
    transFat: 0,
    cholesterol: 30,
    sodium: 200,
    potassium: 100,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 100,
  },
  {
    name: "Oats",
    amount: "100 gm",
    calories: 389,
    protein: 16.9,
    carbs: 66.3,
    fiber: 10.6,
    sugar: 0,
    fat: 6.9,
    saturatedFat: 1.2,
    polyunsaturatedFat: 2.5,
    monounsaturatedFat: 2.2,
    transFat: 0,
    cholesterol: 0,
    sodium: 2,
    potassium: 429,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 54,
  },
  {
    name: "Banana",
    amount: "1 medium",
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fiber: 3.1,
    sugar: 14,
    fat: 0.3,
    saturatedFat: 0.1,
    polyunsaturatedFat: 0.1,
    monounsaturatedFat: 0.1,
    transFat: 0,
    cholesterol: 0,
    sodium: 1,
    potassium: 422,
    vitaminA: 0,
    vitaminC: 10.3,
    calcium: 5,
  },
  {
    name: "Chicken Breast",
    amount: "100 gm",
    calories: 165,
    protein: 31,
    carbs: 0,
    fiber: 0,
    sugar: 0,
    fat: 3.6,
    saturatedFat: 1,
    polyunsaturatedFat: 0.8,
    monounsaturatedFat: 1.2,
    transFat: 0,
    cholesterol: 85,
    sodium: 74,
    potassium: 256,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 15,
  },
  {
    name: "Avocado",
    amount: "100 gm",
    calories: 160,
    protein: 2,
    carbs: 9,
    fiber: 7,
    sugar: 0.7,
    fat: 15,
    saturatedFat: 2.1,
    polyunsaturatedFat: 1.8,
    monounsaturatedFat: 10,
    transFat: 0,
    cholesterol: 0,
    sodium: 7,
    potassium: 485,
    vitaminA: 146,
    vitaminC: 12,
    calcium: 12,
  },
  {
    name: "Almonds",
    amount: "28 gm",
    calories: 160,
    protein: 6,
    carbs: 6,
    fiber: 3.5,
    sugar: 1,
    fat: 14,
    saturatedFat: 1.1,
    polyunsaturatedFat: 3.5,
    monounsaturatedFat: 9.2,
    transFat: 0,
    cholesterol: 0,
    sodium: 0,
    potassium: 208,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 75,
  },
  {
    name: "Spinach",
    amount: "100 gm",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fiber: 2.2,
    sugar: 0.4,
    fat: 0.4,
    saturatedFat: 0.1,
    polyunsaturatedFat: 0.1,
    monounsaturatedFat: 0.1,
    transFat: 0,
    cholesterol: 0,
    sodium: 79,
    potassium: 558,
    vitaminA: 469,
    vitaminC: 28.1,
    calcium: 99,
  },
  {
    name: "Sweet Potato",
    amount: "100 gm",
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fiber: 3,
    sugar: 4.2,
    fat: 0.1,
    saturatedFat: 0,
    polyunsaturatedFat: 0,
    monounsaturatedFat: 0,
    transFat: 0,
    cholesterol: 0,
    sodium: 55,
    potassium: 337,
    vitaminA: 19218,
    vitaminC: 2.4,
    calcium: 30,
  },
  {
    name: "Egg",
    amount: "1 large",
    calories: 72,
    protein: 6,
    carbs: 0.6,
    fiber: 0,
    sugar: 0.5,
    fat: 5,
    saturatedFat: 1.6,
    polyunsaturatedFat: 0.7,
    monounsaturatedFat: 2,
    transFat: 0,
    cholesterol: 186,
    sodium: 71,
    potassium: 69,
    vitaminA: 270,
    vitaminC: 0,
    calcium: 28,
  },
  {
    name: "Broccoli",
    amount: "100 gm",
    calories: 34,
    protein: 2.8,
    carbs: 6.6,
    fiber: 2.4,
    sugar: 1.7,
    fat: 0.4,
    saturatedFat: 0.1,
    polyunsaturatedFat: 0.1,
    monounsaturatedFat: 0.1,
    transFat: 0,
    cholesterol: 0,
    sodium: 33,
    potassium: 316,
    vitaminA: 623,
    vitaminC: 89.2,
    calcium: 47,
  },
];

// Seed the database
const seedDatabase = async () => {
  try {
    await Food.deleteMany(); // Delete all existing food data to start fresh
    await Food.insertMany(foodData); // Insert the new data
    console.log("Food data seeded successfully");
    mongoose.connection.close(); // Close the database connection
  } catch (error) {
    console.error("Error seeding data:", error);
  }
};

// Run the seeding function
seedDatabase();
